version: '3'
services:
    nginx:
        image: lumieducation/nginx:latest
        restart: always
        ports:
            - ${PORT}:80
        networks:
            - webnet
        volumes:
            - ./files:/usr/share/nginx/html/files
    lumi:
        image: lumieducation/lumi:latest
        restart: always
        networks:
            - webnet
        environment:
            - LUMI_ID=${ID}
            - NODE_ENV=${NODE_ENV}
            - KEY=${KEY}
            - DB_HOST=${DB_HOST}
            - DB=${DB}
        volumes:
            - ./files:/srv/build/upload
            - ./h5p:/srv/build/h5p
        depends_on:
            - 'couchdb'
    changes:
        image: lumieducation/lumi-changes:v1.0.0
        restart: always
        networks:
            - webnet
        environment:
            - KEY=${KEY}
            - NODE_ENV=${NODE_ENV}
            - DB_HOST=${DB_HOST}
            - DB=${DB}
        depends_on:
            - 'couchdb'
    apd:
        image: lumieducation/apd:master
        privileged: true
        restart: always
        ports:
            - '53:53'
        network_mode: 'host'
    couchdb:
        image: matthiasg/rpi-couchdb:2.0.0
        restart: always
        volumes:
            - ./db:/opt/couchdb/data
        networks:
            - webnet
        ports:
            - '5984:5984'
networks:
    ? webnet
